"""Schema Updates

Revision ID: 1023960d2d0a
Revises: 90a9961bc847
Create Date: 2024-01-05 18:02:22.005724

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1023960d2d0a"
down_revision: Union[str, None] = "90a9961bc847"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("order_items_order_id_key", "order_items", type_="unique")
    op.drop_constraint("order_items_product_id_key", "order_items", type_="unique")
    op.drop_constraint("orders_customer_id_key", "orders", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("orders_customer_id_key", "orders", ["customer_id"])
    op.create_unique_constraint(
        "order_items_product_id_key", "order_items", ["product_id"]
    )
    op.create_unique_constraint("order_items_order_id_key", "order_items", ["order_id"])
    # ### end Alembic commands ###
