"""Schema Updates

Revision ID: 155131564b80
Revises: 1023960d2d0a
Create Date: 2024-01-05 20:10:05.115672

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "155131564b80"
down_revision: Union[str, None] = "1023960d2d0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order_items", sa.Column("price", sa.Float(), nullable=True))
    op.drop_column("order_items", "sub_total")
    op.drop_column("orders", "sub_total")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "sub_total",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "order_items",
        sa.Column(
            "sub_total",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("order_items", "price")
    # ### end Alembic commands ###
