"""Schema Updates

Revision ID: 8acce1eda07d
Revises: 70ada074abfc
Create Date: 2024-01-05 17:59:36.636887

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8acce1eda07d"
down_revision: Union[str, None] = "70ada074abfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "inventories", "product_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_unique_constraint(None, "inventories", ["product_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "inventories", type_="unique")
    op.alter_column(
        "inventories", "product_id", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
